In [3]:
pip list --not-required

Package   Version
--------- -------
ipykernel 7.1.0
numpy     2.3.4
pip       24.3.1
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import time

In [4]:
# Array creation From list
arr_list = np.array([1, 2, 3, 4, 5])

# Using built-in functions
even_array = np.arange(0, 100, 2)        # Even numbers
linear_space_array = np.linspace(0, 5, 50)       # 50 equally spaced numbers from 0 to 5
matrix = np.random.randint(10, 100, size=(3, 3))  # Random 3x3 array

# display 
print("Array from list:", arr_list)
print("Arange array:", even_array)
print("Linspace array:", linear_space_array)
print("Random array:\n", matrix)

Array from list: [1 2 3 4 5]
Arange array: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
Linspace array: [0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
Random array:
 [[73 28 26]
 [64 73 56]
 [14 77 33]]
