In [2]:
pip list --not-required

Package   Version
--------- -------
ipykernel 7.1.0
numpy     2.3.4
pip       24.3.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import time

In [4]:
# Array creation From list
arr_list = np.array([1, 2, 3, 4, 5])

# Using built-in functions
even_array = np.arange(0, 100, 2)        # Even numbers
linear_space_array = np.linspace(0, 5, 50)       # 50 equally spaced numbers from 0 to 5
matrix = np.random.randint(10, 100, size=(3, 3))  # Random 3x3 array

# display 
print("Array from list:", arr_list)
print("Arange array:", even_array)
print("Linspace array:", linear_space_array)
print("Random array:\n", matrix)

Array from list: [1 2 3 4 5]
Arange array: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
Linspace array: [0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]
Random array:
 [[99 85 91]
 [21 92 40]
 [30 72 71]]


In [5]:
# Indexing & Slicing
# -----------------------

print("\t\tIndexing & Slicing")
print(f"{'-'*50}",end='\n\n')

print(f"First element of {arr_list[0] = }")
print(f"Last two elements {arr_list[-2:] = }")
print(f"Subarray {matrix[0:2, 1:3] = }")


		Indexing & Slicing
--------------------------------------------------

First element of arr_list[0] = np.int64(1)
Last two elements arr_list[-2:] = array([4, 5])
Subarray matrix[0:2, 1:3] = array([[85, 91],
       [92, 40]], dtype=int32)


In [6]:
'''
Numpy Array provide four main type slicing
1. basic slicing - use : and index like arr[row,col]
2. integer array indexing - access element at arbitary position
3. Boolean indexing - access element based on condition
4. indexing combination - access element combine above three combo
'''

# basic slicing 
arr = np.arange(1, 13).reshape(3, 4)
print(f"{arr[0:2, 1:3] = }")  # rows 0-1, cols 1-2
print(f"{arr[::2, ::-1] = }") # all second row , reverse all element

# integer array indexing 
row = np.array([1,2])
col = np.array([2,3])

print(f'{arr[row,col] = }') # pick (1,2), (2,3)

# boolean indexing 
one_dim_array = np.arange(13)
print(f'{one_dim_array[one_dim_array % 2 == 0] = }')

# combination of slicing
print(f'{one_dim_array[(one_dim_array > 3) & (one_dim_array < 8)]}') # pick element in grater than 3 less than 8

arr[0:2, 1:3] = array([[2, 3],
       [6, 7]])
arr[::2, ::-1] = array([[ 4,  3,  2,  1],
       [12, 11, 10,  9]])
arr[row,col] = array([ 7, 12])
one_dim_array[one_dim_array % 2 == 0] = array([ 0,  2,  4,  6,  8, 10, 12])
[4 5 6 7]


In [7]:
# Mathematical & Statistical Operations
# -----------------------------------------

array = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", array)

# sum of array 
print("Sum:", np.sum(array))
print("Axis 0 Sum:", np.sum(array, axis=0))
print("Axis 1 Sum:", np.sum(array, axis=1))

# mean of array 
print('Mean:',np.mean(array))
print("Axis 0 Mean:", np.mean(array, axis=0))
print("Axis 1 Mean:", np.mean(array, axis=1))

# Standard Deviation
print("Standard Deviation:", np.std(array))
print("Axis 0 Standard Deviation:", np.std(array, axis=0))
print('Axis 1 Standard Deviation:', np.std(array, axis=1))

# variance
print('Variance:', np.var(array))

# Median of Array
print('Median:',np.median(array))
print('Axis 0 Median:',np.median(array, axis=0))
print('Axis 1 Median:',np.median(array, axis=1))

# min max and range of array 
print('Min:', np.min(array))
print('Max:', np.max(array))
print('Average:', np.average(array))
print('Range (Max - Min):', np.ptp(array))

# z-score 
z_score = (array - np.mean(array)) / np.std(array)
print("Z-Score:", z_score)

Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Axis 0 Sum: [5 7 9]
Axis 1 Sum: [ 6 15]
Mean: 3.5
Axis 0 Mean: [2.5 3.5 4.5]
Axis 1 Mean: [2. 5.]
Standard Deviation: 1.707825127659933
Axis 0 Standard Deviation: [1.5 1.5 1.5]
Axis 1 Standard Deviation: [0.81649658 0.81649658]
Variance: 2.9166666666666665
Median: 3.5
Axis 0 Median: [2.5 3.5 4.5]
Axis 1 Median: [2. 5.]
Min: 1
Max: 6
Average: 3.5
Range (Max - Min): 5
Z-Score: [[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [8]:
# Skewness and Kurtosis 
print("Skewness (manual):", np.mean((array - np.mean(array))**3) / np.std(array)**3)
print("Kurtosis (manual):", np.mean((array - np.mean(array))**4) / np.std(array)**4 - 3)

Skewness (manual): 0.0
Kurtosis (manual): -1.2685714285714282


In [9]:
# Correlation and Covariance

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print("Correlation Matrix:\n", np.corrcoef(x, y))
print("Covariance Matrix:\n", np.cov(x, y))

Correlation Matrix:
 [[1. 1.]
 [1. 1.]]
Covariance Matrix:
 [[ 2.5  5. ]
 [ 5.  10. ]]


In [10]:
example = np.array([0, -2, -1, -5, 1, 2, 3, 4, 5, 6])

print("Absolute:", np.abs(example))
print("Square:", np.square(example))
print("Square root:", np.sqrt(np.abs(example)))
print("Exponential:", np.exp2(example)) # 2^{x}
print("Logarithm:", np.log(np.abs(example) + 1))
print("Clip (limit values):", np.clip(example, min= -1, max= 1))

Absolute: [0 2 1 5 1 2 3 4 5 6]
Square: [ 0  4  1 25  1  4  9 16 25 36]
Square root: [0.         1.41421356 1.         2.23606798 1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974]
Exponential: [1.000e+00 2.500e-01 5.000e-01 3.125e-02 2.000e+00 4.000e+00 8.000e+00
 1.600e+01 3.200e+01 6.400e+01]
Logarithm: [0.         1.09861229 0.69314718 1.79175947 0.69314718 1.09861229
 1.38629436 1.60943791 1.79175947 1.94591015]
Clip (limit values): [ 0 -1 -1 -1  1  1  1  1  1  1]


In [11]:
# Reshaping & Broadcasting
# ------------------------------

new_arr = np.arange(1,13).reshape(3, 4)
print("Reshaped 3x4 array:\n", new_arr)


Reshaped 3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
new_arr = np.arange(1,13).reshape(-1, 6)  # -1 use for auto asign the size
print("Reshaped 2x6 array:\n", new_arr)

new_arr = np.arange(1,13).reshape(3, -1)  # -1 use for auto asign the size
print("Reshaped 3x4 array:\n", new_arr)

Reshaped 2x6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Reshaped 3x4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
# flatten the mutidimentional array 

print('Raveled array:',new_arr.ravel())    # returns a view (faster)
print('Flatten:',new_arr.flatten())  # returns copy

Raveled array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
# expand dimention
print('expand Axis 0 :',np.expand_dims(array,axis=0).shape)
print('expand Axis 1 :',np.expand_dims(array,axis=1).shape)

expand Axis 0 : (1, 2, 3)
expand Axis 1 : (2, 1, 3)


In [15]:
# Broadcasting Rules
# NumPy have brocasting certian rules that known as golden rules there are,
# 1. Align from the rightmost dimensions
# 2. Dimensions must be equal or one of them must be 1
# 3. If unequal and neither is 1

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(A.shape) # (2, 3)
print(b.shape) # (3,)

print(A + b)


(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


In [ ]:
# 3D tensor Broadcasting

A = np.random.rand(2, 3, 1) 
B = np.random.rand(1, 3, 4)

print(f'{A = }')
print(f'{B = }')


print((A + B).shape) #(2, 3, 4)


A = array([[[0.4759507 ],
        [0.51560426],
        [0.94013181]],

       [[0.31858174],
        [0.99584406],
        [0.537043  ]]])
B = array([[[0.05241599, 0.62278606, 0.24632393, 0.84158608],
        [0.77426137, 0.04903074, 0.5694683 , 0.37112748],
        [0.09039439, 0.04964255, 0.90301322, 0.96594731]]])
(2, 3, 4)


In [ ]:
array_1 = np.array([1, 3, 4])
array_2 = np.array([2, 4, 5, 6])

print(array_1.shape) # (3,)
print(array_2.shape) # (4,)

array_1 = array_1[:,np.newaxis] # (3, 1)

result = array_1 + array_2 

print(f'{result = }')
print(f'{result.shape = }')

(3,)
(4,)
result = array([[ 3,  5,  6,  7],
       [ 5,  7,  8,  9],
       [ 6,  8,  9, 10]])
result.shape = (3, 4)


In [25]:
# Normalization
X = np.random.rand(50, 7)
mean = X.mean(axis=0)
std = X.std(axis=0)
X_norm = (X - mean) / std 

# print(f'{X = }')
print(f'{mean = }')
print(f'{std = }')
print(f'{X_norm = }')

mean = array([0.50696413, 0.47049312, 0.53729609, 0.48471138, 0.44272687,
       0.44531278, 0.52265567])
std = array([0.29007922, 0.29440578, 0.27222101, 0.26915499, 0.26165124,
       0.29804178, 0.29498965])
X_norm = array([[-6.62241495e-01,  1.14240565e+00,  5.26214687e-01,
        -1.49061586e+00,  4.87399431e-01, -1.37440061e+00,
         1.38890599e+00],
       [ 1.69103458e+00,  7.99013005e-01, -8.58936460e-02,
        -1.56692609e-01, -1.27906993e+00, -1.43379013e+00,
         8.86238758e-01],
       [ 2.89050458e-01, -3.01735127e-01,  9.94993102e-01,
         1.82976089e+00,  8.48889819e-02,  6.50480026e-01,
        -1.03843941e+00],
       [ 1.54017251e+00, -8.37309718e-01, -5.57916250e-01,
        -1.45975021e+00, -1.65033978e+00, -2.11469383e-01,
         7.11822595e-01],
       [ 3.55458255e-01,  1.63745531e+00, -1.93259108e+00,
        -3.49367231e-01, -7.41229817e-02,  7.47741146e-02,
        -1.71461887e+00],
       [-1.62508812e-01,  1.41338118e+00,  5.86713008e-02,
 

In [45]:
# Save & Load of NumPy Arrays

# load csv file to NumPy
csv_file = r'src\input_file\gender_submission.csv'
dataset = np.genfromtxt(csv_file,delimiter=',', dtype= None, encoding='utf-8',skip_header=1)

print(f'{dataset = }')
print(f'{dataset.shape = }') # (418,2)

# Save NumPy Array into CSV format 
file_name = 'NumpyToCsv'
path = 'src/output_file/' + file_name + '.csv'
try:
    np.savetxt(path, dataset, delimiter=',', fmt='%d', header='col1,col2')
    print(f'File Saved Succefully in Path of : {path}')
except Exception as E:
    print(f'ERROR : {E}')

dataset = array([[ 892,    0],
       [ 893,    1],
       [ 894,    0],
       [ 895,    0],
       [ 896,    1],
       [ 897,    0],
       [ 898,    1],
       [ 899,    0],
       [ 900,    1],
       [ 901,    0],
       [ 902,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    0],
       [ 910,    1],
       [ 911,    1],
       [ 912,    0],
       [ 913,    0],
       [ 914,    1],
       [ 915,    0],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    0],
       [ 920,    0],
       [ 921,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    1],
       [ 925,    1],
       [ 926,    0],
       [ 927,    0],
       [ 928,    1],
       [ 929,    1],
       [ 930,    0],
       [ 931,    0],
       [ 932,    0],
       [ 933,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
   